[project]
name = "oui"
version = "0.1.0"
description = "Some configurations for Open WebUI"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "jupyter>=1.1.1",
    "open-webui>=0.6.26",
    "pyexecjs>=1.5.1",
    "serpapi>=0.1.5",
]
